"""Adicionando classe modelo

Revision ID: 1888b1a85062
Revises: 
Create Date: 2025-10-03 13:16:10.923534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1888b1a85062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campos_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campo_texto', sa.String(length=150), nullable=False),
    sa.Column('campo_texto_limitado', sa.String(length=10), nullable=False),
    sa.Column('campo_email', sa.String(length=150), nullable=False),
    sa.Column('campo_numero', sa.Integer(), nullable=False),
    sa.Column('campo_data', sa.Date(), nullable=False),
    sa.Column('campo_selecao', sa.Integer(), nullable=False),
    sa.Column('chk_habilitado', sa.Boolean(), nullable=False),
    sa.Column('chk_desabilitado', sa.Boolean(), nullable=False),
    sa.Column('rb_resposta', sa.String(length=1), nullable=False),
    sa.Column('area_texto', sa.String(length=450), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campos_teste')
    # ### end Alembic commands ###
