"""add event logs

Revision ID: dddfbb362638
Revises: 4e9269885d78
Create Date: 2025-09-29 10:02:50.529867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddfbb362638'
down_revision = '4e9269885d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('event_log', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_event')
    # ### end Alembic commands ###
